theme = "hugo-resume"
languageCode = "en-us"

title = "Zach Bryhtan"
baseURL = "https://bryhtan.github.io/"


[params]
address = "Iowa"
email = "zachary-bryhtan@uiowa.edu"
favicon = "/icon/favicon.ico"
firstName = "Zachary"
lastName = "Bryhtan"
phone = "1-800-SUH-DUDE"
profileImage = "images/Pythagoras.jpeg"

showEducation = true
showTeaching = true
showConferences = true
showExperience = false
showOpenSource = false
showProjects = false
showPublications = true
showQr = false
showSkills = false
showCertifications = false
showBlog = true

[[params.handles]]
link = "https://www.linkedin.com/in/zachary-bryhtan/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/bryhtan/"
name = "GitHub"


# ==============================================================================
# No need to change anything below here
# ==============================================================================

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"


PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
